### ISSUE TITLE
RFC: Choose a stack

### ISSUE THREAD

**Issue by iamclaytonray** [pondenome/prototype#6]
It does not look like we have chosen a final stack. Because chat apps like Rocket and Slack are hard to go back to and reference conversations, especially as more conversations are added, I thought this would be a great place to collab on what languages, frameworks, and tools we will use to build the end product.

Backend:

- Go
- Rust
- JavaScript (Node)
- C#
- Java

Frontend:

- React
- Angular
- Vue
- Polymer
- Vanilla JS

We could also leverage newer technologies, such as WASM and Blockchain, for various features. I could see Blockchain fitting in for security and auth, and I could see WASM fitting in for performance-critical functionality. We could probably utilize WASM for things like media, compression, and so on, so we can remove that from JS for much higher efficiency.

One last thought. I just added a few options. As far as languages go, there are so many and I really didn't feel like listing them all. If you don't see a language, library, framework, or technology that you think should belong here, drop a comment so that it can be added to the OP, making it easier for others to collaborate as well.

**Comment by robguinness** [comment]
Great that you picked up on this! Yes, we have been discussing stack for some time in the #dev channel, but it is difficult to follow the thread. What we (preliminarily) decided was to start prototyping using Meteor, which is a Javascript/Node platform. It has some flexibility in terms of front-end technologies. We haven't decided on anything in that respect, but several expressed a preference for Vue.

I want to point out that we should think about this as a prototype stack. I think the goal should be to get to an MVP as quickly as possible. It seems we are limited on amount of time people have for development work at the moment, so leveraging bootstrapping platforms like Meteor are going to help. As we build out though, we can replace bits and pieces with more efficient/scalable technologies, as needed.
